#debug: true

# PROFILES  项目接口
## dev | prod | trds
spring:
  application:
     name: product-service
server:
  port: 8060
---
spring:
  profiles: test

# Connection url for the database "51qed"
spring.datasource:
  url:  jdbc:mysql://192.168.1.215:3306/lihe?zeroDateTimeBehavior=convertToNull

# Username and password
  username :  apidba
  password :  XFcaPhvbc=6m
logging:
  level:
    path:  /opt/logs/lihe
    file:  ${spring.application.name}/${spring.application.name}.log
---
spring:
  profiles: prod
  datasource:
      url:  jdbc:mysql://10.168.234.100:3306/lihe?zeroDateTimeBehavior=convertToNull
      #Username and password
      username :  apidba
      password :  saMewAY1991@*&1
logging:
  level:
    path:  /opt/logs/lihe
    file:  ${spring.application.name}/${spring.application.name}.log
